<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/04/06 15:19:36
sfConfig::add(array(
  'mod_invoicetemplates_enabled' => true,
  'mod_invoicetemplates_view_class' => 'sfPHP',
));
