<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/04/06 12:55:04
sfConfig::add(array(
  'mod_usercategories_enabled' => true,
  'mod_usercategories_view_class' => 'sfPHP',
));
