<?php
// auto-generated by sfSecurityConfigHandler
// date: 2022/04/06 12:04:40
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'user' => 
  array (
    'is_secure' => false,
  ),
  'group' => 
  array (
    'is_secure' => false,
  ),
  'ifccallback' => 
  array (
    'is_secure' => false,
  ),
  'ifc' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
